config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  resources :carousel_pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :invoices
  resources :practice_rink_reservations
  root 'application#index'

  resources :players do
    collection do
      get :autocomplete
    end
  end
  resources :teams
  resources :news_articles
  resources :committee_pages
  resources :committee_members
  resources :games
  resources :leagues
  resources :player_teams
  resources :player_games

  get '/residencyindex', to: 'players#residencyindex'
  post 'import', to: 'players#import'

  get '/schedulegames', to: 'games#schedulegames'
  post '/schedulegames', to: 'games#creategamesschedule'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'playergamestats/:id' => 'games#playergamestats', as: 'player_game_stats'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

end

app/controllers/practice_rink_reservations_controller.rb
class PracticeRinkReservationsController < ApplicationController
  before_action :set_practice_rink_reservation, only: [:show, :edit, :update, :destroy]

  # GET /practice_rink_reservations
  # GET /practice_rink_reservations.json
  def index
    @practice_rink_reservations = PracticeRinkReservation.all
  end

  # GET /practice_rink_reservations/1
  # GET /practice_rink_reservations/1.json
  def show
  end

  # GET /practice_rink_reservations/new
  def new
    @practice_rink_reservation = PracticeRinkReservation.new
  end

  # GET /practice_rink_reservations/1/edit
  def edit
  end

  # POST /practice_rink_reservations
  # POST /practice_rink_reservations.json
  def create
    @practice_rink_reservation = PracticeRinkReservation.new(practice_rink_reservation_params)

    respond_to do |format|
      if @practice_rink_reservation.save
        format.html { redirect_to @practice_rink_reservation, notice: 'Practice rink reservation was successfully created.' }
        format.json { render :show, status: :created, location: @practice_rink_reservation }
      else
        format.html { render :new }
        format.json { render json: @practice_rink_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practice_rink_reservations/1
  # PATCH/PUT /practice_rink_reservations/1.json
  def update
    respond_to do |format|
      if @practice_rink_reservation.update(practice_rink_reservation_params)
        format.html { redirect_to @practice_rink_reservation, notice: 'Practice rink reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @practice_rink_reservation }
      else
        format.html { render :edit }
        format.json { render json: @practice_rink_reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practice_rink_reservations/1
  # DELETE /practice_rink_reservations/1.json
  def destroy
    @practice_rink_reservation.destroy
    respond_to do |format|
      format.html { redirect_to practice_rink_reservations_url, notice: 'Practice rink reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice_rink_reservation
      @practice_rink_reservation = PracticeRinkReservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_rink_reservation_params
      params.require(:practice_rink_reservation).permit(:team_id, :paid)
    end
end

app/helpers/practice_rink_reservations_helper.rb
module PracticeRinkReservationsHelper
end

app/views/practice_rink_reservations/_form.html.erb
<%= form_for(@practice_rink_reservation) do |f| %>
  <% if @practice_rink_reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@practice_rink_reservation.errors.count, "error") %> prohibited this practice_rink_reservation from being saved:</h2>

      <ul>
      <% @practice_rink_reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.text_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :paid %><br>
    <%= f.check_box :paid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/practice_rink_reservations/edit.html.erb
<h1>Editing Practice Rink Reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @practice_rink_reservation %> |
<%= link_to 'Back', practice_rink_reservations_path %>

app/views/practice_rink_reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Practice Rink Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @practice_rink_reservations.each do |practice_rink_reservation| %>
      <tr>
        <td><%= practice_rink_reservation.team_id %></td>
        <td><%= practice_rink_reservation.paid %></td>
        <td><%= link_to 'Show', practice_rink_reservation %></td>
        <td><%= link_to 'Edit', edit_practice_rink_reservation_path(practice_rink_reservation) %></td>
        <td><%= link_to 'Destroy', practice_rink_reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Practice rink reservation', new_practice_rink_reservation_path %>

app/views/practice_rink_reservations/new.html.erb
<h1>New Practice Rink Reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', practice_rink_reservations_path %>

app/views/practice_rink_reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @practice_rink_reservation.team_id %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @practice_rink_reservation.paid %>
</p>

<%= link_to 'Edit', edit_practice_rink_reservation_path(@practice_rink_reservation) %> |
<%= link_to 'Back', practice_rink_reservations_path %>