config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  resources :carousel_pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :invoices
  resources :practice_rink_reservations
  root 'application#index'

  resources :players do
    collection do
      get :autocomplete
    end
  end
  resources :teams
  resources :news_articles
  resources :committee_pages
  resources :committee_members
  resources :games
  resources :leagues
  resources :player_teams
  resources :player_games

  get '/residencyindex', to: 'players#residencyindex'
  post 'import', to: 'players#import'

  get '/schedulegames', to: 'games#schedulegames'
  post '/schedulegames', to: 'games#creategamesschedule'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'playergamestats/:id' => 'games#playergamestats', as: 'player_game_stats'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

end

app/views/shared/_footer.html.erb
<!--Partial used for Footer-->
  <footer class="footer">
      <div class="container-fluid">
      	<div class="row">
      		<div class="col-xs-4">
      			<!--TODO: Make year dynamic when we reach 2017 -->
	        	<h5 class="footer-text">Ⓒ Broomball 2016</h5>
	        </div>
	        <div class="col-xs-4 text-center logo">
	        	<a href="https://www.mtu.edu">
	        		<img src="/assets/mtulogo.png" width="74" height="46"/>	
	        	</a>
	        </div>
	        <!--Icons found at iconfinder.com-->
	        <div class="col-xs-4">
		        <ul class="nav navbar-nav navbar-right">
		        	<li class="col-xs-3 footer-icons">
		        		<a href="https://twitter.com/irhcbroomball">
		        			<img border="0" alt="Twitter" src="/assets/icons/twitter.png" width="24" height="24">
						</a>
					</li>
		        	<li class="col-xs-3 footer-icons">
		        		<a href="https://www.facebook.com/irhcbroomball">
							<img border="0" alt="Facebook" src="/assets/icons/facebook.png" width="24" height="24">
						</a>
					</li>
		        	<li class="col-xs-3 footer-icons">
		        		<a href="https://twitter.com/irhcbroomball">
							<img border="0" alt="Flickr" src="/assets/icons/flickr.png" width="24" height="24">	
						</a>
					</li>
					<li class="col-xs-3 footer-icons">
		        		<a href="https://www.youtube.com/user/IRHCBroomball">
							<img border="0" alt="Youtube" src="/assets/icons/youtube.png" width="24" height="24">	
						</a>
					</li>	
		        </ul>
	        </div>
        </div>
      </div>
  </footer>

app/views/shared/_navigation.html.erb
<!--link_to Reference: http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to-->
<!--TODO: Update to RESTful Routes-->
<!--Partial used for Navigation bar-->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%=link_to "/", class:"navbar-brand" do%>
     	<span class="glyphicon glyphicon-home" aria-hidden="true"></span> Broomball
	  <% end %>
    </div>
    <ul class="nav navbar-nav navbar-right">
    	<!--Dropdown for Currently Logged in User-->
      <% if current_player %>
    	<li class="dropdown">
        	<a class="dropdown-toggle hidden-sm" data-toggle="dropdown" href="#">My Broomball
        	<span class="caret"></span></a>
        	<a class="dropdown-toggle visible-sm" data-toggle="dropdown" href="#">
        	<span data-toggle="tooltip" title="My Broomball" data-placement="auto bottom" class="glyphicon glyphicon-user visible-sm"></span></a>
        	<ul class="dropdown-menu">
        		<li><%=link_to "My Profile", player_path(current_player.id)%></li>
            <li><%=link_to "Game Schedule", games_path(player: current_player.id)%></li>
        	</ul>
      	</li>
        <% end %>
      	<!--Dropdown for teams-->
      	<li class="dropdown">
        		<a class="dropdown-toggle hidden-sm" data-toggle="dropdown" href="">Teams
          	<span class="caret"></span></a>
          	<a class="dropdown-toggle visible-sm" data-toggle="dropdown" href="#">
          	<span data-toggle="tooltip" title="Teams" data-placement="auto bottom" class="glyphicon glyphicon-list visible-sm"></span></a>
        		<ul class="dropdown-menu">
        			<li><%=link_to "All Teams", teams_path%></li>
        			<li class="divider"></li>
        			<!--TODO: Limit Teams to 40 character names-->
              <% current_player_teams.each do |team| %>
        			<li><%=link_to truncate(team.name), team_path(team.id)%></li>
              <% end %>
          	</ul>
    		</li>
    		<!--Link to Schedule (list view)-->
      	<li><a href="#"><div class="hidden-sm">Schedule</div><span data-toggle="tooltip" title="Schedule" data-placement="auto bottom" class="glyphicon glyphicon-calendar visible-sm"></span></a></li>

        <!--Search bar form-->
        <%= form_tag players_path, :class => "navbar-form navbar-left", :role => "search", method: :get do %>
          <div class="form-group">
            <%= text_field_tag :query, params[:query], autocomplete: :off, class: 'form-control', placeholder: "Search for player/team", id: "players_search" %>
          </div>
          <%= button_tag 'Search', name: nil, :class => "btn btn-sm" do %>
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
          <% end %>
        <% end %>

        <!--Dropdown for more links-->
      	<li class="dropdown">
      		<a class="dropdown-toggle hidden-sm" data-toggle="dropdown" href="#">More
        	<span class="caret"></span></a>
        	<a class="dropdown-toggle visible-sm" data-toggle="dropdown" href="#">
        	<span data-toggle="tooltip" title="More" data-placement="auto bottom" class="glyphicon glyphicon-menu-down visible-sm"></span></a>
      		<ul class="dropdown-menu">
      			<li><a href="#">About</a></li>
      			<li><a href="#">Contact</a></li>
      			<!--TODO: Hide this option if not a committee member-->
      			<li><%=link_to "Committee", controller: "committee_pages", action: "index"%></li>
        	</ul>
		</li>
	    <li class="dropdown">
	        <% if current_user %>
		<%= link_to signout_path, id: "sign_out" do %>
		<strong><%= current_user.name %></strong>, Signout
		<% end %>
		<% else %>
		<%= link_to "/auth/google_oauth2", id: "sign_in" do %>
		Sign in <span class="glyphicon glyphicon-log-in"></span>
		<% end %>
		<% end %>
	    </li>
    </ul>
  </div>
</nav>