config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  resources :carousel_pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :invoices
  resources :practice_rink_reservations
  root 'application#index'

  resources :players do
    collection do
      get :autocomplete
    end
  end
  resources :teams
  resources :news_articles
  resources :committee_pages
  resources :committee_members
  resources :games
  resources :leagues
  resources :player_teams
  resources :player_games

  get '/residencyindex', to: 'players#residencyindex'
  post 'import', to: 'players#import'

  get '/schedulegames', to: 'games#schedulegames'
  post '/schedulegames', to: 'games#creategamesschedule'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'playergamestats/:id' => 'games#playergamestats', as: 'player_game_stats'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

end

app/models/game.rb
class Game < ApplicationRecord
  has_many :player_games
  has_many :players, :through => :player_games

  belongs_to :home_team, :class_name => :Team
  belongs_to :away_team, :class_name => :Team

  def self.creategames(startDate)
    schedule=RRSchedule::Schedule.new(
    :teams => [
      %w(A1 A2 A3 A4 A5 A6 A7 A8 A9 A10),
      %w(B1 B2 B3 B4 B5 B6 B7 B8 B9 B10),
      %w(C1 C2 C3 C4 C5 C6 C7 C8 C9 C10),
      %w(D1 D2 D3 D4 D5 D6 D7 D8 D9 D10),
      %w(E1 E2 E3 E4 E5 E6 E7 E8 E9 E10),
      %w(F1 F2 F3 F4 F5 F6 F7 F8 F9 F10),
      %w(G1 G2 G3 G4 G5 G6 G7 G8 G9 G10),
      %w(H1 H2 H3 H4 H5 H6 H7 H8 H9 H10),
      %w(I1 I2 I3 I4 I5 I6 I7 I8 I9 I10),
      %w(J1 J2 J3 J4 J5 J6 J7 J8 J9 J10),
      %w(K1 K2 K3 K4 K5 K6 K7 K8 K9 K10),
      %w(L1 L2 L3 L4 L5 L6 L7 L8 L9 L10),
      %w(M1 M2 M3 M4 M5 M6 M7 M8 M9 M10),
      %w(N1 N2 N3 N4 N5 N6 N7 N8 N9 N10),
      %w(O1 O2 O3 O4 O5 O6 O7 O8 O9 O10),
      %w(P1 P2 P3 P4 P5 P6 P7 P8 P9 P10),
      %w(Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9 Q10),
      %w(R1 R2 R3 R4 R5 R6 R7 R8 R9 R10),
      %w(S1 S2 S3 S4 S5 S6 S7 S8 S9 S10),
      %w(T1 T2 T3 T4 T5 T6 T7 T8 T9 T10),
      %w(U1 U2 U3 U4 U5 U6 U7 U8 U9 U10),
      %w(V1 V2 V3 V4 V5 V6 V7 V8 V9 V10),
      %w(W1 W2 W3 W4 W5 W6 W7 W8 W9 W10),
      %w(X1 X2 X3 X4 X5 X6 X7 X8 X9 X10)
    ],

    #Setup some scheduling rules
    :rules => [
      RRSchedule::Rule.new(:wday => 0, :gt => ["8:00AM", "8:45AM", "9:30AM", "10:15AM", "11:00AM", "11:45AM", "12:30PM", "1:15PM", "2:00PM", "2:45PM", "3:30PM", "4:15PM", "5:00PM", "5:45PM", "6:30PM", "7:15PM", "8:00PM", "8:45PM", "9:30PM", "10:15PM", "11:00PM"], :ps => ["black", "silver", "gold"]),
      RRSchedule::Rule.new(:wday => 1, :gt => ["5:00PM", "5:45PM", "6:30PM", "7:15PM", "8:00PM", "8:45PM", "9:30PM", "10:15PM", "11:00PM"], :ps => ["black", "silver", "gold"]),
      RRSchedule::Rule.new(:wday => 2, :gt => ["5:00PM", "5:45PM", "6:30PM", "7:15PM", "8:00PM", "8:45PM", "9:30PM", "10:15PM", "11:00PM"], :ps => ["black", "silver", "gold"]),
      RRSchedule::Rule.new(:wday => 3, :gt => ["5:00PM", "5:45PM", "6:30PM", "7:15PM", "8:00PM", "8:45PM", "9:30PM", "10:15PM", "11:00PM"], :ps => ["black", "silver", "gold"]),
      RRSchedule::Rule.new(:wday => 4, :gt => ["5:00PM", "5:45PM", "6:30PM", "7:15PM", "8:00PM", "8:45PM", "9:30PM", "10:15PM", "11:00PM"], :ps => ["black", "silver", "gold"]),
      RRSchedule::Rule.new(:wday => 5, :gt => ["5:00PM", "5:45PM", "6:30PM", "7:15PM", "8:00PM", "8:45PM", "9:30PM", "10:15PM", "11:00PM"], :ps => ["black", "silver", "gold"]),
      RRSchedule::Rule.new(:wday => 6, :gt => ["8:00AM", "8:45AM", "9:30AM", "10:15AM", "11:00AM", "11:45AM", "12:30PM", "1:15PM", "2:00PM", "2:45PM", "3:30PM", "4:15PM", "5:00PM", "5:45PM", "6:30PM", "7:15PM", "8:00PM", "8:45PM", "9:30PM", "10:15PM", "11:00PM"], :ps => ["black", "silver", "gold"])
    ],

    #First games are played on...
    :start_date => Date.parse("2017/01/10"),

    #array of dates to exclude
    :exclude_dates => [],

    #Number of times each team must play against each other (default is 1)
    :cycles => 1,

    #Shuffle team order before each cycle. Default is true
    :shuffle => true
  )

  schedule.generate
  schedule.gamedays.each do |gd|
    gd.games.each do |g|
      dt = g.game_time
      dtStart = DateTime.new(gd.date.year, gd.date.month, gd.date.day, g.game_time.hour, g.game_time.min, g.game_time.sec, g.game_time.zone)
      Game.create(home_team_id: Team.where(name: g.team_a.to_s).first.id, away_team_id: Team.where(name: g.team_b.to_s).first.id, start_time: dtStart, end_time: dtStart + 45.minutes, rink: g.ps)
    end
  end


  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :playergamestats]

  # GET /games
  # GET /games.json
  def index
    player = params[:player].present? ? params[:player] : nil
    @games = if player
      Game.joins(:players).where('players.id = ?', player)
    else
      Game.all
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit

  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      byebug
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def schedulegames
    @games=Game.all
  end

  def creategamesschedule
    begin
      Game.creategames("test")
      redirect_to '/schedulegames', notice: "Games Successfully Scheduled!"
    rescue
      redirect_to '/schedulegames', notice: "Unable to Schedule Games"
    end
  end

  def playergamestats

    @home_team_players = []
    @home_team_player_games = []
    @game.home_team.players.each do |htp|
      pg = PlayerGame.where(player: htp, game: @game).first_or_create
      @home_team_players << htp
      @home_team_player_games << pg
    end

    @away_team_players = []
    @away_team_player_games = []
    @game.away_team.players.each do |atp|
      pg = PlayerGame.where(player: atp, game: @game).first_or_create
      @away_team_players << atp
      @away_team_player_games << pg
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.fetch(:game).permit(:home_goals, :away_goals, :overtime_loss)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.label :home_goals %>
    <%= form.number_field :home_goals %><br>

    <%= form.label :away_goals %>
    <%= form.number_field :away_goals %><br>

    <%= form.label :overtime_loss %>
    <%= form.check_box :overtime_loss %><br>





    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<div id="calendar"></div>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/playergamestats.html.erb
<h1>Enter Player Stats</h1>

<%= form_tag player_games_path do %>



    <% @away_team_player_games.each_with_index do |away_team_player_game, i| %>
      <% # form.label @home_team_players[i].first_name + " " + @home_team_players[i].last_name  %>
      <%= fields_for "away_team_player_games[]", away_team_player_game do |f| %> <%= f.label :goals %> <%= f.number_field :goals %> <%= f.label :assists %> <%= f.number_field :assists %> <%= f.label :saves %> <%= f.number_field :saves %> <% end %>
    <% end %>
    <div class="actions">
      <%= submit_tag "Submit" %>
    </div>

<% end %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/schedulegames.html.erb
<div class="panel panel-default">
	<div class="panel-heading article-title">Schedule Games</div>
	<div class="panel-body">
		

		<%= form_tag schedulegames_path, multipart: true do %>
			<%= submit_tag "Schedule" %>
		<% end %>
	</div>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to @game.home_team.name, team_path(@game.home_team) %>
<%= link_to @game.away_team.name, team_path(@game.away_team) %>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>