config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  resources :carousel_pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :invoices
  resources :practice_rink_reservations
  root 'application#index'

  resources :players do
    collection do
      get :autocomplete
    end
  end
  resources :teams
  resources :news_articles
  resources :committee_pages
  resources :committee_members
  resources :games
  resources :leagues
  resources :player_teams
  resources :player_games

  get '/residencyindex', to: 'players#residencyindex'
  post 'import', to: 'players#import'

  get '/schedulegames', to: 'games#schedulegames'
  post '/schedulegames', to: 'games#creategamesschedule'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'playergamestats/:id' => 'games#playergamestats', as: 'player_game_stats'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  root to: "home#show"

end

app/models/player.rb
class Player < ApplicationRecord
  searchkick word_start: [:first_name, :last_name, :mtu_id]

  has_many :player_games
  has_many :games, :through => :player_games

  has_many :player_teams
  has_many :teams, :through => :player_teams

  mount_uploader :profile_pic, ImageUploader

  require 'csv'
  require 'active_record'
  require 'activerecord-import'

  def self.residencyimport(file)
    players = []
    CSV.foreach(file.path, headers: true) do |row|
      player_hash = row.to_hash
      players << Player.new(first_name: player_hash["first_name"], last_name: player_hash["last_name"], mtu_id: player_hash["mtu_id"])
    end
    Player.import players
  end

  def full_name
      "#{first_name} #{last_name}"
    end

  def search_data
    {
      full_name: full_name,
      first_name: first_name,
      last_name: last_name,
      mtu_id: mtu_id
    }
  end


  private
    def image_size_validation
      errors[:profile_pic] << "should be less than 500KB" if profile_pic.size > 0.5.megabytes
    end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  before_action :set_player, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update]
  before_action :authenticate_admin, only: [:destroy, :create, :import, :residencyindex]

  # GET /players
  # GET /players.json
  def index
    search = params[:query].present? ? params[:query] : nil
    @players = if search
      Player.search(search)
    else
      Player.all
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @playerstats=Player.joins(:teams, :player_games, :player_teams).select('players.first_name, players.last_name, teams.id as team_id, teams.name, teams.season_id, sum(player_games.goals) as goals, sum(player_games.assists) as assists, sum(player_games.saves) as saves').where(id: @player.id).group('teams.id')
    @totalgoals=0
    @totalassists=0
    @totalsaves=0
    @hasaccess=has_access
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update_attributes(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def residencyindex
    @players=Player.all
  end

  def import
    begin
      Player.residencyimport(params[:file])
      redirect_to '/residencyindex', notice: "Residency Data Imported!"
    rescue
      redirect_to '/residencyindex', notice: "Invalid CSV file format"
    end
  end

  def autocomplete
    test = params[:query]
    t=Player.search(params[:query], fields: ['first_name', 'last_name', 'mtu_id', 'full_name'], match: :word_start, limit: 10)
    render json: t.map{|p| "#{p.first_name} #{p.last_name} (#{p.mtu_id})"}
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:mtu_id, :first_name, :last_name, :nickname, :email, :profile_pic, :remove_profile_pic, :major, :hometown, :position, :height_feet, :height_inches, :years_played, :description, :autocomplete)
    end

    # Check if user is logged in and has access to resource
    def authenticate_user
      if !current_user
        redirect_to "/auth/google_oauth2", :id => "sign_in" and return
      elsif current_user.mtu_id != @player.mtu_id && !Player.exists?(mtu_id: current_user.mtu_id, committee: true)
        redirect_to player_path(@player), notice: "The signed in user account cannot access this resource" and return
      end
    end

    # Check if user is logged in as admin
    def authenticate_admin
      if !current_user
        redirect_to "/auth/google_oauth2", :id => "sign_in" and return
      elsif !Player.exists?(mtu_id: current_user.mtu_id, committee: true)
        if @player
          redirect_to player_path(@player), notice: "The signed in user account cannot access this resource" and return
        else
          redirect_to players_path, notice: "The signed in user account cannot access this resource" and return
        end
      end
    end

    # Check if the user has permissions to do further actions (edit/update player)
    def has_access
      if !current_user
        return false
      elsif current_user.mtu_id != @player.mtu_id && !Player.exists?(mtu_id: current_user.mtu_id, committee: true)
        return false
      end
      return true
    end

end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

    <%= f.label :nickname %>
    <%= f.text_field :nickname %><br>

    <%= f.label :major %>
    <%= f.text_field :major %><br>

    <%= f.label :hometown %>
    <%= f.text_field :hometown %><br>

    <%= f.label :position %>
    <%= f.text_field :position %><br>

    <%= f.label :years_played %>
    <%= f.text_field :years_played %><br>

    <%= f.label :description %>
    <%= f.text_area :description %><br>

    <%= f.label :profile_pic %><br>
    <%= f.file_field :profile_pic %>
    <% if f.object.profile_pic? %>
      <%= image_tag f.object.profile_pic.thumb.url %>
      <%= f.label :remove_profile_pic %>
      <%= f.check_box :remove_profile_pic %>
    <% end %>

    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<div class="panel panel-default">
	<div class="panel-heading article-title">Edit Player</div>
	<div class="panel-body">
		<%= render 'form', player: @player %>
	</div>
</div>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<!--This page will be used to list players-->

<div class="container-fluid table-responsive">
	<h2 class="table-title"><span>Team Name</span></h2>
	<table class="table table-hover active">
		<thead>
    		<tr>
		      <th>Player Name</th>
		      <th>Nick Name</th>
		      <th>Position</th>
		      <th>Goals</th>
		      <th>Assists</th>
		      <th>Points</th>
    		</tr>
  		</thead>
  		<tbody>

			<% @players.each do |player| %>
				<tr>
					<td><%= link_to (player.first_name + " " + player.last_name), player_path(player.id) %></td>
					<td><%= player.nickname %></td>
					<td><%= player.position %></td>
					<td><%= player.goals %></td>
					<td><%= player.assists %></td>
					<td></td>
				</tr>
			<% end %>

			<% if @players.size == 0 %>
				<em>No Players Found</em>
			<% end %>

		</tbody>
	</table>
</div>

app/views/players/listPlayers.html.erb
<!--This page will be used to list players-->

<div class="container-fluid table-responsive">
	<h2 class="table-title"><span>Team Name</span></h2>
	<table class="table table-hover active">
		<thead>
    		<tr>
		      <th>Player Name</th>
		      <th>Nick Name</th>
		      <th>Position</th>
		      <th>Goals</th>
		      <th>Assists</th>
		      <th>Points</th>
    		</tr>
  		</thead>
  		<tbody>	
  			<%10.times do%>	
			<tr>
				<td>Nick Fisher</td>
				<td>Fish</td>
				<td>Left Wing</td>
				<td>23</td>
				<td>9</td>
				<td>32</td>
			</tr>
			<%end%>
		</tbody>
	</table>
</div>

app/views/players/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading article-title">New Player</div>
	<div class="panel-body">
		<%= render 'form', player: @player %>
	</div>
</div>

<%= link_to 'Back', players_path %>

app/views/players/residencyindex.html.erb
<%provide(:title, "Residency Import")%>

<% if flash[:notice] %>
   <div class="notice"><%= flash[:notice] %></div>
 <% end %>

 <div class="panel panel-default">
 	<div class="panel-heading article-title">Edit Player</div>
 	<div class="panel-body">
    <h4>Import residency</h4>
      <%= form_tag import_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import CSV" %>
      <% end %>
  </div>
</div>

app/views/players/schedule.html.erb
<h1>Players#schedule</h1>
<p>Find me in app/views/players/schedule.html.erb</p>

app/views/players/show.html.erb
<%provide(:title, @player.first_name + " " + @player.last_name)%>

<div class="container-fluid table-responsive">
	<div class="row">
		<div class="col-xs-4 profile-pic">
			<% if @player.profile_pic? %>
			<%= image_tag @player.profile_pic.url, class:"img-responsive img-circle" %>
			<% else %>
			<img src="/assets/profile_pictures/nafisher/profile_test.jpg" class="img-responsive img-circle" alt="">
			<% end %>
			<% if @hasaccess %>
			<button class="btn btn-xs pic-btn">Change <span class="glyphicon glyphicon-pencil"></span></button>
			<% end %>
		</div>
		<div class="col-xs-8">
			<div class="panel panel-default">
				<div class="panel-heading"> <%= @player.first_name + " " + @player.last_name %>
					<% if @hasaccess %> <%= link_to edit_player_path, class:"btn btn-xs edit-btn" do %>Edit <span class="glyphicon glyphicon-pencil"></span> <% end %> <% end %> </div>
  				<div class="panel-body">
					<div class="row">
						<div class="col-xs-6" id="desc-col">
							<b>Name:  </b> <span><%= @player.first_name %> <% if @player.nickname? %> <%= " \'" + @player.nickname + "\'" %> <% end %> <%=" " + @player.last_name %></span><br>
							<b>Major:</b> <span><%= @player.major %></span> <br>
							<b>Hometown:</b> <span><%= @player.hometown %></span><br>
							<b>Position:</b> <span><%= @player.position %></span><br>
							<b>Height:</b> <span><% if @player.height_feet? && @player.height_inches? %> <%= "#{@player.height_feet}\' #{@player.height_inches}\'\'" %> <% end %></span><br>
							<b>Years played:</b> <span><%= @player.years_played %></span><br>
						</div>

						<div class="col-xs-6">
							<h5>Player Description:</h5>
						<%= @player.description %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<h2 class="table-title"><span>Teams & Statistics</span></h2>
	<table class="table table-hover active">
		<thead>
    		<tr>
		      <th>Season</th>
		      <th>Team</th>
		      <th>Goals</th>
		      <th>Assists</th>
		      <th>Penalty Minutes</th>
		      <th>Saves</th>
		      <th>Goalie Minutes</th>
		      <th>Goals Against</th>
    		</tr>
  	</thead>
  		<tbody>
				<%= @playerstats.each do |pt| %>
				<% @totalgoals+=pt.goals %>
				<% @totalassists+=pt.assists %>
				<% @totalsaves+=pt.saves %>
				<tr>
					<td><%= pt.season_id %></td>
					<td><%= link_to pt.name, team_path(pt.team_id) %></td>
					<td><%= pt.goals %></td>
					<td><%= pt.assists %></td>
					<td>TODO</td>
					<td><%= pt.saves %></td>
					<td>TODO</td>
					<td>TODO</td>
				</tr>
				<% end %>

			<tr>
				<td><b>Total</b></td>
				<td>--</td>
				<td><%= @totalgoals %></td>
				<td><%= @totalassists %></td>
				<td>TODO</td>
				<td><%= @totalsaves %></td>
				<td>TODO</td>
				<td>TODO</td>
			</tr>
		</tbody>
	</table>
</div>

app/views/players/stats.html.erb
<!--Might just incorporate stats into the profile page-->